### ISSUE TITLE
i can't view map

### ISSUE THREAD

**Issue by tazel7885** [rsasaki0109/pcl_localization_ros2#21]
https://github.com/HViktorTsoi/FAST_LIO_LOCALIZATION

i use map.pcd and rosbag file in above git link

when i launch your code i can't see map on rviz

what's your perception_pcl library? 
https://github.com/ros-perception/perception_pcl          <- is that??

**Comment by rsasaki0109** [comment]
Is map_path set correctly? Please check it in the terminal output.

> map_path: "$HOME/github_ws/ros2_ws/src/pcl_localization_ros2/map/bin_tc-2017-10-15--ndmap.pcd"
https://github.com/rsasaki0109/pcl_localization_ros2/blob/main/param/localization.yaml#L12

>   RCLCPP_INFO(get_logger(),"map_path: %s", map_path_.c_str());
https://github.com/rsasaki0109/pcl_localization_ros2/blob/main/src/pcl_localization_component.cpp#L178

**Comment by rsasaki0109** [comment]
> what's your perception_pcl library?
https://github.com/ros-perception/perception_pcl <- is that??

Yes, this package is using pcl_conversions from perception_pcl.

**Comment by tazel7885** [comment]
https://github.com/rsasaki0109/lidarslam_ros2

i make pcd map using above git. And data is hdl_400.bag

But my result is bad. 

i use parameter under!

is there any wrong?

/**:
    ros__parameters:
      registration_method: "NDT"
      ndt_resolution: 3.0
      ndt_step_size: 0.1
      transform_epsilon: 0.01
      voxel_leaf_size: 1.0
      scan_max_range: 100.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/tazel7885/ros2_ws/src/pcl_localization_ros2/map/map.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 1.0
      use_odom: false
      use_imu: true
      enable_debug: true

**Comment by tazel7885** [comment]
![Screenshot from 2023-03-30 18-55-31](https://user-images.githubusercontent.com/48857469/228800599-432e7a2e-56de-4763-85ba-6d6617240308.png)

**Comment by tazel7885** [comment]
my result

**Comment by tazel7885** [comment]
![path](https://user-images.githubusercontent.com/48857469/228800717-95d94459-fd21-4cfd-a4ab-a5ea66fe8cab.png)

this is git result

**Comment by rsasaki0109** [comment]
I'll check.

**Comment by rsasaki0109** [comment]
`ndt_resolution` and `voxel_leaf_size` may be too large. Could you try with the following parameter set?

  | ndt_resolution | voxel_leaf_size
-- | -- | --
1 | 2.0 | 1.0
2 | 2.0 | 0.5
3 | 1.0 | 0.5
4 | 1.0 | 0.2

**Comment by tazel7885** [comment]
i test all. but result is same.

Just in case, it seems that the map data and sensor data do not match inside the code. Is there any way to check if the map has been loaded from inside the code?

**Comment by rsasaki0109** [comment]
> Is there any way to check if the map has been loaded from inside the code?

Currently, there is no such function, but you can have the message output at the following

https://github.com/rsasaki0109/pcl_localization_ros2/blob/main/src/pcl_localization_component.cpp#L76-L96

**Comment by rsasaki0109** [comment]
It was confirmed that localization is possible with the following parameters

```
/**:
    ros__parameters:
      registration_method: "GICP"
      ndt_resolution: 1.0
      ndt_step_size: 0.1
      transform_epsilon: 0.01
      voxel_leaf_size: 0.5
      scan_max_range: 100.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/sasaki/Downloads/hdl_data/map.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 1.0
      use_odom: false
      use_imu: false
      enable_debug: true
```

![image](https://user-images.githubusercontent.com/18298605/229044020-7d03bc60-b7cf-4c33-9c76-1209f59a537e.png)
